#  端口号和上下文路径配置
server:
  port: 8123
  servlet:
    context-path: /api
    #  cookie 过期时间设置为30天
    session:
      cookie:
        max-age: 2592000  # 30天，单位为秒
#起个名字
spring:
  application:
    name: my-spring-boot-app

# 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_image
    username: root
    password: 123456
#    文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
#      redis配置
  redis:
    host: localhost
    port: 6379
    database: 1
    connect-timeout: 5000
    password: redis_password

#  session配置
  session:
    store-type: redis
    timeout: 2592000        # 30分钟




#mybatis-plus配置
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #debug日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #逻辑删除
    global-config:
      db-config:
        logic-delete-field: isDeleted
        logic-delete-value: 1
        logic-not-delete-value: 0


#接口文档
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v4.0
    group:
      test1:
        group-name: 默认组
        api-rule: package
        api-rule-resources:
          - com.polar.cloudimage.controller


